BookTechSite/Controllers/AuthorsController.cs
using BookTechSite.Services;
using System.Web.Mvc;
using BookTechSite.Models;

namespace BookTechSite.Controllers
{
    public class AuthorsController : Controller
    {
        IAuthorRepository repo;

        public AuthorsController(IAuthorRepository repo)
        {
            this.repo = repo;
        }

        public ViewResult Index()
        {
            ViewBag.CountOfAuthors = repo.GetCountOfAuthors();
            return View(repo.GetAuthorsAndBookTitles());
        }

        public ActionResult LoadDataSqlBulkCopyAuthorsBooks()
        {
            repo.LoadDataSqlBulkCopyAuthorsBooks();
            return RedirectToAction("index");
        }

        public ViewResult Details(int id)
        {
            AuthorBooksViewModel authorBooksVM = repo.GetAuthorAndBooks(id);
            //return authorBooksVM == null ? EntityNotFound() : View(authorBooksVM);
            return View(authorBooksVM);
        }

        [HttpPost]
        public ActionResult Details(AuthorBooksViewModel vm)
        {
            // when Authorise payment button is pressed

            // if the tick box has been pressed (almost view logic, so leave it in the controller)
            //var service = new BPAService();
            //service.AuthorisePaymentToAuthorOnAllTheirBooksWhichAreOutstanding(vm.AuthorID);

            return RedirectToAction("index");
        }

        // Using a GET so URL is copyable
        [HttpGet]
        public ActionResult Search(string lastName = "")
        {
            var authors = repo.SearchByLastName(lastName);
            return View(authors);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Author author)
        {
            if (ModelState.IsValid)
            {
                repo.Create(author);
                return RedirectToAction("index");
            }
            return View(author);
        }

        public ActionResult Edit(int id)
        {
            var author = repo.GetAuthorByID(id);
            //if (author == null) return EntityNotFound();
            return View(author);
        }

        [HttpPost]
        public ActionResult Edit(Author author)
        {
            if (ModelState.IsValid)
            {
                repo.UpdateAuthor(author);
                return RedirectToAction("index");
            }

            return View(author);
        }

        public ActionResult Delete(int authorID)
        {
            repo.Delete(authorID);
            return RedirectToAction("index");
        }
    }
}

BookTechSite/Views/Shared/EntityNotFoundError.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "Error";
}

<h1 class="text-danger">Not found</h1>
<p>We looked, but it wasn't there.</p>
<p>We've logged this problem.</p>

BookTechSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
@using StackExchange.Profiling;
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book Publishing Corp Admin</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Book Publishing Corp Admin", "Index", "Authors", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@*@Html.ActionLink("Home", "Index", "Home")*@</li>
                    <li>@*@Html.ActionLink("Authors", "Index", "Authors")*@</li>
                    <li>@Html.ActionLink("Books", "Index", "Books")</li>
                </ul>
                @Html.Partial("_LoginPartial")
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("LoadDataSqlBulkCopyAuthorsBooks", "LoadDataSqlBulkCopyAuthorsBooks", "Authors")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @MiniProfiler.RenderIncludes()
</body>
</html>